// Seeded defaults for every content block (ANTE-ADMIN §4.4).
// A missing content_blocks row must never render an empty page: getContent falls back
// here. These strings are also the seed data for the content_blocks table.
// The rulebook's voice is the target register — dry, deadpan, never zany.

export const contentDefaults: Record<string, string> = {
  // Homepage
  "home.logo_alt": "ANTE",
  "home.intro_heading": "The room is forming.",
  "home.intro_body":
    "A season-long NFL chip pool. Everyone starts with 500. Nobody sees a pick until everyone is locked in. Biggest stack on the last Sunday wins.",
  "home.phone_label": "Phone number",
  "home.phone_placeholder": "(555) 555-0100",
  "home.phone_cta": "Send code",
  "home.code_prompt": "Enter the six-digit code we texted you.",
  "home.legal_line": "Chips have no cash value. None. Ever.",
  "home.copyright": "© 2026 The Ante Game",
  "home.pending_message":
    "You're on the list. The Commissioner reviews every application before Week 1. You'll get a text when you're in.",
  "home.closed_message":
    "The roster locked at the Week 1 deadline. Everybody starts at 500 on the same Thursday or not at all. There's always next season.",
  "home.verify_cta": "Verify",
  "home.resend_label": "Send a new code",

  // Onboarding / profile
  "profile.heading": "Take your seat",
  "profile.intro_body": "Four questions and you're in the room.",
  "profile.first_name_label": "First name",
  "profile.last_name_label": "Last name",
  "profile.email_label": "Email",
  "profile.favorite_team_label": "Favorite team",
  "profile.submit_label": "Continue",
  "profile.error_generic": "That didn't take. Try again.",

  // Dashboard
  "dash.header_rank_label": "Rank",
  "dash.header_chips_label": "Chips",
  "dash.logout_label": "Log out",
  "dash.wager.heading": "This week",
  "dash.wager.closed_message": "The slate opens Tuesday at 6:00am ET.",
  "dash.wager.submitted_message": "Your ticket is in. Locked. No edits — not by you, not by anyone.",
  "dash.wager.blackout_notice": "Nobody sees a pick until everyone is in.",
  "dash.wager.waiting_on_label": "Waiting on",
  "dash.wager.confirm_title": "Push your chips in?",
  "dash.wager.confirm_body":
    "Submitting locks this ticket. It cannot be changed — not by you, not by the Commissioner, not for injuries, weather, or regret.",
  "dash.wager.shove_warning":
    "The shove commits your entire stack to one game at even money. Once per season. No other bets this week. Type SHOVE to confirm.",
  "dash.wager.ante_label": "Ante paid",
  "dash.wager.limit_label": "House limit",
  "dash.wager.committed_label": "Committed",
  "dash.wager.remaining_label": "Remaining",
  "dash.wager.games_label": "Games",
  "dash.wager.submit_cta": "Push your chips in",
  "dash.wager.confirm_cta": "Lock it",
  "dash.wager.cancel_cta": "Not yet",
  "dash.wager.shove_mode_cta": "The shove",
  "dash.wager.shove_spent_label": "Shove spent — Week {week}",
  "dash.wager.shove_commit_note": "You'll push {stake}, including the {ante} ante coming back at the reveal.",
  "dash.wager.shove_dark_note": "Nobody will know until the reveal. Not even the Commissioner.",
  "dash.wager.spread_note": "The spread is context. Bets settle straight-up — winner wins.",
  "dash.wager.felt_notice": "You're on the felt: bet what you have, on whatever you want.",
  "dash.wager.capped_room": "capped by the room",
  "dash.wager.capped_stack": "capped by your stack",
  "dash.wager.min_games_note": "Pick at least {min} games.",
  // Notification templates (ADMIN §4.7) — email season one (D-001)
  "notify.slate_open": "Week {week} is open. The ante was {ante}; your limit is {limit}. Thursday noon is the wall.",
  "notify.reminder": "Week {week}: {hours_left} hours to the wall, and your name is on the waiting list.",
  "notify.final_call": "Final call for Week {week}. Submit by noon ET or you're folded — and you still owe the ante.",
  "notify.nudge": "The room is waiting on you. Everyone can see it.",
  "notify.reveal": "The room is open — every Week {week} ticket is live.",
  "notify.settled": "Week {week} settled: {delta} on the week. Stack {stack}, rank {rank}.",
  "notify.pot": "{winner} takes the Week {week} Pot: +{amount}.",
  "notify.correction": "Commissioner correction on Week {week}: {reason}. Every correction is public.",

  // Stakes band (art §3 — the one big colored plane)
  "band.week_label": "Week",
  "band.tier_purple": "Purple tier",
  "band.tier_red": "Red tier",
  "band.tier_teal": "Teal tier",
  "band.tier_gold": "Gold tier",
  "band.ante_label": "Ante",
  "band.pot_label": "The Pot",
  "band.limit_label": "Your limit",
  "band.deadline_label": "Deadline",
  "band.preseason_message": "Preseason. The roster is forming — Week 1 locks {lock}.",

  // Ticker system items (ADMIN §4.5.3 — wording is content-managed)
  "ticker.deadline": "Thursday noon ET — {remaining}",
  "ticker.waiting_on": "{in} of {total} in — waiting on {names}",
  "ticker.pot": "This week's Pot: {pot} chips",
  "ticker.marker": "The Pot is carrying a {marker}-chip marker",
  "ticker.reveal": "The room is open — every ticket is live",
  "ticker.leader": "{name} leads with {stack}",

  // Promo box (fields editable in the admin console)
  "promo.heading": "",
  "promo.body": "",
  "promo.cta_label": "",
  "promo.cta_url": "",
  "promo.image_url": "",

  // Season page
  "season.standings_heading": "Final standings",
  "season.awards_heading": "Awards",
  "season.unclaimed": "unclaimed",
  "season.mark_label": "The Mark",
  "season.mark_open": "ballot open — felt finishers only",
  "season.not_closed": "Computed when the season closes. Every ticket stays readable forever.",
  "season.mark_vote_heading": "The Mark — your vote",
  "season.mark_vote_body": "You finished on the felt, which makes this yours to give. One vote. Anyone is nominable.",
  "season.cast_cta": "Cast it",
  "dash.wager.total_label": "Total",
  "reveal.you_label": "you",

  "reveal.interstitial_title": "The room is open",
  "reveal.interstitial_sub": "Every ticket. Every chip. Nothing can change now.",
  "reveal.enter_cta": "See the board",
  "reveal.shove_beat_title": "A shove",
  "reveal.shove_beat_body": "{name} pushed everything. {stake} on {team}, even money. It moved every price on the board.",
  "reveal.by_game_label": "By game",
  "reveal.by_player_label": "By player",
  "reveal.folded_label": "Folded",
  "reveal.shove_label": "Shove",
  "reveal.pays_label": "pays",
  "reveal.nobody_label": "Nobody",
  "dash.leaderboard.heading": "Standings",
  "dash.leaderboard.empty": "No stacks to show yet.",
  "lb.rank": "#",
  "lb.player": "Player",
  "lb.stack": "Stack",
  "lb.delta": "Δ wk",
  "lb.won": "W",
  "lb.lost": "L",
  "lb.win_pct": "Win %",
  "lb.pots": "Pots",
  "lb.folds": "Folds",
  "lb.avg_mult": "Avg ×",
  "lb.shove": "Shove",
  "lb.shove_held": "Held",
  "lb.felt_badge": "Felt",
  "lb.out_badge": "Out",
  "settled.heading": "Week {week} — settled",
  "settled.delta_label": "Your week, ante included",
  "settled.pot_label": "The Pot",
  "settled.pot_none": "Nobody took the Pot this week. It rolls.",
  "settled.pot_marker": "The table is into the Pot for {marker}. The marker carries.",
  "settled.stack_label": "Your stack",
  "settled.rank_label": "Rank",
  "settled.won_label": "Won",
  "settled.lost_label": "Lost",
  "settled.returned_label": "Returned",
  "dash.tabletalk.heading": "Table Talk",
  "dash.tabletalk.placeholder": "Say it to the whole room…",
  "dash.tabletalk.muted_notice": "You're muted until {expiry}. You can read, and you can still bet.",
  "dash.tabletalk.tombstone": "— a message was hidden by the Commissioner —",
  "dash.news.heading": "Your team",
  "dash.news.empty": "Quiet day. Nothing worth reading.",
  "dash.promo.fallback_heading": "ANTE",
  "dash.support.heading": "Need a human?",
  "dash.support.body": "Email the desk. Complaints must be notarized and set on fire, but questions are fine.",
  "dash.support.email": "support@theantegame.com",

  // Rules / awards / misc
  "rules.intro":
    "The complete rules, frozen for the season. Versioned with the code — nobody can edit these at 11pm, including the Commissioner.",
  "awards.intro": "They cost nothing. They carry more weight than they should.",
  "sms.optin_disclosure":
    "We'll text you a login code now and league updates during the season. Reply STOP anytime to opt out of updates.",
  "error.404": "There's nothing here. There may never have been.",
  "error.500": "Something broke on our end. The ledger is fine. It's always fine.",
  "empty.no_games": "No games on the slate.",
  "empty.no_news": "Nothing to report.",
};

export type ContentKey = keyof typeof contentDefaults;
