// Seeded defaults for every content block (ANTE-ADMIN §4.4).
// A missing content_blocks row must never render an empty page: getContent falls back
// here. These strings are also the seed data for the content_blocks table.
// The rulebook's voice is the target register — dry, deadpan, never zany.

export const contentDefaults: Record<string, string> = {
  // Homepage
  "home.logo_alt": "ANTE",
  "home.intro_heading": "The room is forming.",
  "home.intro_body":
    "A season-long NFL chip pool. Everyone starts with 500. Nobody sees a pick until everyone is locked in. Biggest stack on the last Sunday wins.",
  "home.phone_label": "Phone number",
  "home.phone_placeholder": "(555) 555-0100",
  "home.phone_cta": "Send code",
  "home.code_prompt": "Enter the six-digit code we texted you.",
  "home.legal_line": "Chips have no cash value. None. Ever.",
  "home.copyright": "© 2026 The Ante Game",
  "home.pending_message":
    "You're on the list. The Commissioner reviews every application before Week 1. You'll get a text when you're in.",
  "home.closed_message":
    "The roster locked at the Week 1 deadline. Everybody starts at 500 on the same Thursday or not at all. There's always next season.",
  "home.verify_cta": "Verify",
  "home.resend_label": "Send a new code",

  // Onboarding / profile
  "profile.heading": "Take your seat",
  "profile.intro_body": "Four questions and you're in the room.",
  "profile.first_name_label": "First name",
  "profile.last_name_label": "Last name",
  "profile.email_label": "Email",
  "profile.favorite_team_label": "Favorite team",
  "profile.submit_label": "Continue",
  "profile.error_generic": "That didn't take. Try again.",

  // How-to-play tutorial (gate between profile complete and dashboard)
  "howto.heading": "How this works",
  "howto.intro": "Five steps, two minutes, no chips move. Then you're in the room.",
  "howto.step_label": "Step {step} of {total}",
  "howto.next_cta": "Next",
  "howto.back_cta": "Back",
  "howto.skip_cta": "Skip to the end",
  "howto.accept_cta": "I've got it — take me in",
  "howto.error_generic": "That didn't take. Try again.",











  "howto.table_title": "Everyone starts even",
  "howto.table_body": "You have 500 chips. So does everyone else. Every week costs you an ante \u2014 10 chips to start \u2014 and all of those antes go into the Pot. Biggest stack on the last Sunday of the season wins.",
  "howto.bet_title": "Press a team to back it",
  "howto.bet_body": "Every game has two sides. Press the team you like. Press it again to raise \u2014 10, 20, 30, 40, 50 \u2014 and one more press takes the bet back off the table. Try it on any game below.",
  "howto.edge_title": "Here is the real game",
  "howto.edge_body": "You do not get paid by the odds. You get paid by how many people were against you, divided by how many were with you. Back the team everyone else backs and you win almost nothing. Be the only one on your side and be right, and you get up to two and a half times your bet. So do not hunt for the safe pick. Hunt for the game where you think the room is wrong.",
  "howto.reveal_title": "Nobody sees a thing until everyone is in",
  "howto.reveal_body": "Until the last ticket lands you cannot see one pick \u2014 not a team, not a chip, not even a count. Then the room opens and every ticket in the league turns over at once, and you find out whether you were alone on your side or standing with the crowd.",
  "howto.pot_title": "The Pot goes to the biggest week",
  "howto.pot_body": "Every ante sits in the Pot, and at the end of the week the whole thing goes to whoever gained the most chips. Playing it safe keeps you alive. Being different is how you win Pots.",
  "howto.ready_title": "That's it",
  "howto.ready_body": "Four tiers, one season, nobody eliminated. Take your seat.",

  // Dashboard
  "dash.commissioner_link_label": "Commissioner",
  "dash.header_rank_label": "Rank",
  "dash.header_chips_label": "Chips",
  "dash.logout_label": "Log out",
  "dash.guide_link_label": "How to Play",
  "dash.tutorial_link_label": "Tutorial",
  "guide.heading": "How to Play",
  "guide.intro": "ANTE is a season-long football pool. You bet chips on NFL games. The biggest stack on the last Sunday wins. Here is the whole thing in plain English.",
  "guide.back_cta": "Back to the game board",
  "guide.tutorial_cta": "Run the tutorial again",
  "guide.rules_cta": "Read the full rulebook",
  "guide.rules_note": "This page is the short version. The rulebook is the real thing, and it wins any argument.",
  "guide.start_title": "You start with 500 chips",
  "guide.start_body": "Everyone in the league starts with the same 500 chips. Nobody can buy more. Chips are just points \u2014 they are never worth money. The season runs from Week 1 to Week 18.",
  "guide.ante_title": "Every week you pay an ante",
  "guide.ante_body": "An ante is a small fee you pay before you bet. Everyone pays it, even if you sit the week out. It starts at 10 chips and grows to 30 chips by the end of the season. Every ante goes straight into the Pot.",
  "guide.pick_title": "Pick games and put chips on them",
  "guide.pick_body": "The slate opens Tuesday at 6:00am ET. Pick the team you like in each game, then put chips on it. You bet in tens: at least 10 chips on a game, and no more than 50. You have to bet at least 5 games. You cannot bet both teams in the same game. The deadline is Thursday at 12:00 noon ET, every single week.",
  "guide.lock_title": "Once you send it in, it is locked",
  "guide.lock_body": "When you submit your picks, you cannot change them. Neither can the Commissioner. So take your time before you press the button. If you send nothing by Thursday noon, you folded for the week \u2014 and you still pay the ante.",
  "guide.limit_title": "The house limit keeps you safe",
  "guide.limit_body": "There is a cap on how many chips you can bet in one week. It is one third of your own stack, or one third of the league's middle stack \u2014 whichever is smaller. So you can never lose everything in a single week. It also stops a big leader from running away from everyone else.",
  "guide.blackout_title": "Nobody sees anything until everyone is in",
  "guide.blackout_body": "Before the reveal you cannot see anyone's picks. Not their teams, not their chips, not even a count. Nothing on the screen moves. The only thing you can see is the list of people who have not sent their picks in yet. The reveal happens the moment the last player is in.",
  "guide.payout_title": "How much you win",
  "guide.payout_body": "Your payout depends on how many people took the other side of your game. Take the number of people against you and divide it by the number of people with you \u2014 and you count yourself. So being alone against four is 4 divided by 1. The most you can ever get is 2.5 times your bet. The least is a quarter of it. If nobody took the other side, you get even money. Only the people who bet that same game count.",
  "guide.strategy_title": "How to actually win",
  "guide.strategy_body": "Here is the part people miss. What you win depends on how many players took the other side of your game. If you and nine others all back the same team, you are splitting the room and the win is small \u2014 as low as a quarter of what you bet. If you are the only one on your side against four, that is four against one, and you get the most the game allows: two and a half times your bet.\n\nSo the goal is not to pick the games everyone else is picking. The goal is to find the game where you think the room is wrong, and be right about it. Safe picks keep you alive. Different picks win Pots.\n\nAnd you are betting blind. Nobody sees a single pick until everyone is in. All you have is the spread, the moneyline, and what you know about these specific people \u2014 you already know who takes the prime-time favorite every single week. Reading that is the whole game.",
  "guide.pot_title": "The Pot",
  "guide.flow_title": "Your bets and the Pot are two different things",
  "guide.flow_body": "Two things happen every week and they are easy to mix up. First, your bets: chips move between you and the other players who bet the same games. Nothing is created \u2014 what you win, somebody else lost. Second, the Pot: everyone's ante goes into it, and at the end of the week the whole thing goes to whoever gained the most chips. So your bets decide how far your stack moves, and the Pot is the prize for moving it the most. Playing it safe keeps you alive, but it almost never wins a Pot.",
  "guide.pot_body": "Every ante that week goes into the Pot, and none of it disappears. It goes to whoever gained the most chips that week \u2014 your ante counts in that, so you can win the Pot on a week you finished down, as long as everyone else finished down further. You have to have turned in a ticket: folding pays you nothing. In a league of 8 to 15, one player takes the whole Pot. Bigger leagues pay more places \u2014 one for every 8 players. If every single person folds, nothing is awarded and the Pot rolls into next week.",
  "guide.shove_title": "The shove",
  "guide.shove_body": "Once a season you can go all in. You pick one game and push your whole stack onto it. It ignores the house limit \u2014 that is the point. You pay no ante that week, and you make no other bets. A shove always pays even money: win and you double your stack. Lose and you are on the felt. Nobody sees it coming until the reveal.",
  "guide.felt_title": "The felt",
  "guide.felt_body": "Your stack can never drop below 1 chip. If your stack falls below one full ante, you are on the felt. You stop paying the ante, and the 5-game minimum goes away \u2014 bet what you have, on whatever you want. You are not out. Nobody in this league is ever out.",
  "guide.win_title": "How you win the season",
  "guide.win_body": "Biggest stack after Week 18 wins. If two players tie, we look at who had the most winning bets. Still tied? Most Pots won, then fewest weeks folded, then one public card draw.",
  "dash.wager.heading": "Game Board",
  "dash.wager.closed_message": "The slate opens Tuesday at 6:00am ET.",
  "dash.wager.submitted_message": "Your ticket is in. Locked. No edits — not by you, not by anyone.",
  "dash.wager.blackout_notice": "Nobody sees a pick until everyone is in.",
  "dash.wager.waiting_on_label": "Waiting on",
  "dash.wager.confirm_title": "Push your chips in?",
  "dash.wager.confirm_body":
    "Submitting locks this ticket. It cannot be changed — not by you, not by the Commissioner, not for injuries, weather, or regret.",
  "dash.wager.shove_warning":
    "The shove commits your entire stack to one game at even money. Once per season. No other bets this week. Type SHOVE to confirm.",
  "dash.wager.ante_label": "Ante paid",
  "dash.wager.limit_label": "House limit",
  "dash.wager.committed_label": "Committed",
  "dash.wager.remaining_label": "Remaining",
  "dash.wager.games_label": "Games",
  "dash.wager.submit_cta": "Push your chips in",
  "dash.wager.confirm_cta": "Lock it",
  "dash.wager.cancel_cta": "Not yet",
  "dash.wager.shove_mode_cta": "The shove",
  "dash.wager.shove_spent_label": "Shove spent — Week {week}",
  "dash.wager.shove_commit_note": "You'll push {stake}, including the {ante} ante coming back at the reveal.",
  "dash.wager.shove_dark_note": "Nobody will know until the reveal. Not even the Commissioner.",
  "dash.wager.spread_note":
    "The spread and the moneyline come from the sportsbooks and are frozen when the slate opens. Neither one pays here: bets settle straight-up, and what you win is set by how the room split (rulebook \u00a75).",
  "dash.wager.submit_tooltip":
    "Locks your picks in for the week. You'll get one confirmation first. After that there are no edits \u2014 not by you, not by the Commissioner.",
  "dash.wager.shove_tooltip":
    "Once a season: push your whole stack onto one game. Win and it pays big. Lose and you're on the felt. Nobody sees it until the reveal.",
  "dash.wager.at_label": "at",
  "dash.wager.raise_hint":
    "Back a team by pressing it. Every press raises your stake — one more past {max} takes the bet back off the table.",
  "dash.wager.felt_notice": "You're on the felt: bet what you have, on whatever you want.",
  "dash.wager.capped_room": "capped by the room",
  "dash.wager.capped_stack": "capped by your stack",
  "dash.wager.min_games_note": "Pick at least {min} games.",
  "dash.wager.min_games_note_one": "Pick at least one game.",
  // Notification templates (ADMIN §4.7) — email season one (D-001)
  "notify.slate_open": "Week {week} is open. The ante was {ante}; your limit is {limit}. Thursday noon is the wall.",
  "notify.reminder": "Week {week}: {hours_left} hours to the wall, and your name is on the waiting list.",
  "notify.final_call": "Final call for Week {week}. Submit by noon ET or you're folded — and you still owe the ante.",
  "notify.nudge": "The room is waiting on you. Everyone can see it.",
  "notify.reveal": "The room is open — every Week {week} ticket is live.",
  "notify.settled": "Week {week} settled: {delta} on the week. Stack {stack}, rank {rank}.",
  "notify.pot": "{winner} takes the Week {week} Pot: +{amount}.",
  "notify.correction": "Commissioner correction on Week {week}: {reason}. Every correction is public.",

  // Stakes band (art §3 — the one big colored plane)
  "band.week_label": "Week",
  "band.tier_purple": "Purple tier",
  "band.tier_red": "Red tier",
  "band.tier_teal": "Teal tier",
  "band.tier_gold": "Gold tier",
  "band.ante_label": "Ante",
  "band.pot_label": "The Pot",
  "band.limit_label": "Your limit",
  "band.deadline_label": "Deadline",
  "band.preseason_message": "Preseason. The roster is forming — Week 1 locks {lock}.",

  // Ticker system items (ADMIN §4.5.3 — wording is content-managed)
  "ticker.deadline": "Thursday noon ET — {remaining}",
  "ticker.waiting_on": "{in} of {total} in — waiting on {names}",
  "ticker.pot": "This week's Pot: {pot} chips",
  "ticker.marker": "The Pot is carrying a {marker}-chip marker",
  "ticker.reveal": "The room is open — every ticket is live",
  "ticker.leader": "{name} leads with {stack}",

  // Promo box (fields editable in the admin console)
  "promo.heading": "",
  "promo.body": "",
  "promo.cta_label": "",
  "promo.cta_url": "",
  "promo.image_url": "",

  // Season page
  "season.standings_heading": "Final standings",
  "season.awards_heading": "Awards",
  "season.unclaimed": "unclaimed",
  "season.mark_label": "The Mark",
  "season.mark_open": "ballot open — felt finishers only",
  "season.not_closed": "Computed when the season closes. Every ticket stays readable forever.",
  "season.mark_vote_heading": "The Mark — your vote",
  "season.mark_vote_body": "You finished on the felt, which makes this yours to give. One vote. Anyone is nominable.",
  "season.cast_cta": "Cast it",
  "dash.wager.total_label": "Total",
  "reveal.you_label": "you",

  "reveal.interstitial_title": "The room is open",
  "reveal.interstitial_sub": "Every ticket. Every chip. Nothing can change now.",
  "reveal.enter_cta": "See the board",
  "reveal.shove_beat_title": "A shove",
  "reveal.shove_beat_body": "{name} pushed everything. {stake} on {team}, even money. It moved every price on the board.",
  "reveal.by_game_label": "By game",
  "reveal.by_player_label": "By player",
  "reveal.folded_label": "Folded",
  "reveal.shove_label": "Shove",
  "reveal.pays_label": "pays",
  "reveal.nobody_label": "Nobody",
  "dash.leaderboard.heading": "Standings",
  "dash.leaderboard.empty": "No stacks to show yet.",
  "lb.rank": "#",
  "lb.player": "Player",
  "lb.stack": "Stack",
  "lb.delta": "Δ wk",
  "lb.won": "W",
  "lb.lost": "L",
  "lb.win_pct": "Win %",
  "lb.pots": "Pots",
  "lb.folds": "Folds",
  "lb.avg_mult": "Avg ×",
  "lb.shove": "Shove",
  "lb.shove_held": "Held",
  "lb.felt_badge": "Felt",
  "lb.out_badge": "Out",
  "settled.heading": "Week {week} — settled",
  "settled.delta_label": "Your week, ante included",
  "settled.pot_label": "The Pot",
  "settled.pot_none": "Nobody took the Pot this week. It rolls.",
  "settled.pot_marker": "The table is into the Pot for {marker}. The marker carries.",
  "settled.stack_label": "Your stack",
  "settled.rank_label": "Rank",
  "settled.won_label": "Won",
  "settled.lost_label": "Lost",
  "settled.returned_label": "Returned",
  "dash.tabletalk.heading": "Table Talk",
  "dash.tabletalk.live_label": "Chat with the league",
  "dash.tabletalk.placeholder": "Say it to the whole room…",
  "dash.tabletalk.muted_notice": "You're muted until {expiry}. You can read, and you can still bet.",
  "dash.tabletalk.tombstone": "— a message was hidden by the Commissioner —",
  "dash.news.heading": "Your team",
  "dash.news.source_label": "Source",
  "dash.news.empty": "Quiet day. Nothing worth reading.",
  "dash.promo.fallback_heading": "ANTE",
  "dash.support.cta": "Message the desk",
  "dash.support.dialog_title": "Message the desk",
  "dash.support.dialog_intro": "We already know who you are, so just say what is going on. The Commissioner reads every one of these.",
  "dash.support.placeholder": "What do you need?",
  "dash.support.submit_cta": "Send it",
  "dash.support.cancel_cta": "Never mind",
  "dash.support.sent_title": "Message sent",
  "dash.support.sent_body": "The Commissioner has been told there is a message waiting. When they answer, the reply comes to the email address on your profile \u2014 you do not need to check back here.",
  "dash.support.close_cta": "Done",
  "notify.backup_reminder_subject": "ANTE \u2014 your league backup is due",
  "notify.backup_reminder": "It has been {days} days since you last saved a copy of the league.\n\nOpen the Commissioner console, go to Backups, press \"Download current data\", then press \"I've got the file\" so this stops nagging you.\n\nThis is the only copy that survives losing the database, so it is worth the thirty seconds.",
  "notify.support_new_subject": "ANTE \u2014 new message from {player}",
  "notify.support_new": "{player} sent a message from the dashboard:\n\n{message}\n\nAnswer it in the console under Support.",
  "notify.support_reply_subject": "ANTE \u2014 the Commissioner answered",
  "notify.support_reply": "You wrote:\n\n{original}\n\nThe Commissioner replied:\n\n{reply}",
  "dash.support.heading": "Need a human?",
  "dash.support.body": "Message the desk. Complaints must be notarized and set on fire, but questions are fine.",

  // Rules / awards / misc
  "rules.intro":
    "The complete rules, frozen for the season. Versioned with the code — nobody can edit these at 11pm, including the Commissioner.",
  "awards.intro": "They cost nothing. They carry more weight than they should.",
  "sms.optin_disclosure":
    "We'll text you a login code now and league updates during the season. Reply STOP anytime to opt out of updates.",
  "error.404": "There's nothing here. There may never have been.",
  "error.500": "Something broke on our end. The ledger is fine. It's always fine.",
  "empty.no_games": "No games on the slate.",
  "empty.no_news": "Nothing to report.",
};

export type ContentKey = keyof typeof contentDefaults;
